# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './views/interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(929, 562)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(120, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.fase_1 = QtWidgets.QWidget()
        self.fase_1.setObjectName("fase_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fase_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scroll_analisis = QtWidgets.QScrollArea(self.fase_1)
        self.scroll_analisis.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_analisis.sizePolicy().hasHeightForWidth())
        self.scroll_analisis.setSizePolicy(sizePolicy)
        self.scroll_analisis.setMaximumSize(QtCore.QSize(10000, 10000))
        self.scroll_analisis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_analisis.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_analisis.setWidgetResizable(True)
        self.scroll_analisis.setAlignment(QtCore.Qt.AlignCenter)
        self.scroll_analisis.setObjectName("scroll_analisis")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 873, 434))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.estruct_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.estruct_table.setObjectName("estruct_table")
        self.estruct_table.setColumnCount(0)
        self.estruct_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.estruct_table, 3, 0, 1, 1)
        self.preview_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.preview_table.setObjectName("preview_table")
        self.preview_table.setColumnCount(0)
        self.preview_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.preview_table, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.missed_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.missed_table.setObjectName("missed_table")
        self.missed_table.setColumnCount(0)
        self.missed_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.missed_table, 3, 1, 1, 1)
        self.scroll_analisis.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scroll_analisis)
        self.tabWidget.addTab(self.fase_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 27))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(main_window)
        self.actionAbrir.setObjectName("actionAbrir")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Minería de datos"))
        self.label_2.setText(_translate("main_window", "Estructura"))
        self.label.setText(_translate("main_window", "Preview"))
        self.label_3.setText(_translate("main_window", "Datos faltantes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fase_1), _translate("main_window", "Análisis exploratorio de datos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("main_window", "Tab 2"))
        self.menuArchivo.setTitle(_translate("main_window", "Archivo"))
        self.actionAbrir.setText(_translate("main_window", "Abrir"))
